library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('session/', include('session.urls')),
]

session/urls.py
from django.urls import path
from session.views import signup_view,login_view,logout_view,index

app_name = "session"
urlpatterns = [
    path('signup/', signup_view , name='signup'),
    path('login/',login_view , name= 'login'),
    path('logout/',logout_view , name= 'logout'),
    path('',index, name= 'index')
]

session/models.py
from django.db import models

# Create your models here.

session/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField
from django.forms.widgets import PasswordInput, TextInput
from django.utils.translation import gettext, gettext_lazy as _



class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

    password1 = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
           'style': 'border: black solid px'
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = CharField(
        label=_("Password confirmation"),
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
        strip=False,
        help_text=_("Please enter the same password"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}
        widgets = {
            'username': TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'})
        }
        labels = {
            'username':_("Username")
        }
        
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'}))
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
    )

session/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from session.forms import UserCreateForm,UserLoginForm
import requests

# Create your views here.
def index(request):
    return render(request, 'index.html', {"name": request.user.username })

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('session:index')
    else: 
        form = UserCreateForm()
        if request.method == "POST":
            form = UserCreateForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request,user)
                return redirect('session:index')
        return render(request , "signup.html" , {"form": form})



def login_view(request):
    if request.user.is_authenticated:
        return redirect('session:index')
    else:
        form_login = UserLoginForm()
        if request.method == "POST":
            form_login = UserLoginForm(request=request, data= request.POST)
            if form_login.is_valid():
                user = form_login.get_user()
                login(request,user=user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('session:index')
            else:
                return render (request, 'login.html', context={'form': form_login,'error':form_login.get_invalid_login_error()})
        return render(request , 'login.html', {"form":form_login})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('session:login')
    return HttpResponse()

session/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>First Drip by heavenfreesta</title>
</head>
<body>
    {% csrf_token %}
    <div class="text-center"style="color: black;">Welcome, <b>{{name}}</b></div>
    <form action="{% url 'session:logout' %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type='submit' class="btn btn-danger btn-sm" style="margin-top: 2em;" name='logout-btn'>Logout</button>
    </form>

</body>
</html>

session/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Sign In</title>
</head>

<body>
    <div class="container" style="transform: translateY(30%);">
        <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column; ">
            <div style="padding: 7em; border: 3px solid black;">
                <div class="display-3 text-center mb-4">Log In </div>
                <form action="{% url 'session:login' %}" method="POST">
                    {% csrf_token %}
                    {% for error_message in error %}
                    <p style="font-size: 1.2em">*{{ error_message }}</p>
                    {% endfor %}
                    {% for fields in form %}
                    <div class="form-group">
                        <h5 class="text-center">{{ fields.label }}</h5>
                        {{ fields }}
                    </div>
                    {% endfor %}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <div class="row justify-content-center mt-4">
                        <input type="submit" class="btn btn-success btn-lg col-5 mt-4" value='Login' name="login-btn">
                        <p class='col-7 mt-4'><a href="{% url 'session:signup' %}" style="color: black; font-size: 1.2em;"> Doesn't Have an Account? </a> </p>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</body>

</html>

session/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Sign Up | Story 9 </title>
</head>
<body>
    <div class="container" style="transform: translateY(30%);">
    <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column;">
        <div style="padding: 7em; border: 3px solid black;">
            <div class="display-3 mb-4 text-center">Sign Up</div>
                <form action="{% url 'session:signup' %}" method="POST">
                    {% csrf_token %}
                    {% for fields in form %}
                    <div class="form-group">
                            {% for error in fields.errors %}
                                <p style="font-size: 1.2em">*{{ error }}</p>
                            {% endfor %}
                            <h5 class="text-center">{{ fields.label }}</h5>
                            {{ fields }}
                        </div>
                    {% endfor %}
                    <div class="text-center">
                    <input type="submit" value='Sign Up' class="btn btn-success btn-lg mb-4">
                </form>
        </div>
    </div>    
    </div>    
</body>
</html>